5/28 addFilm 구현중
문제1. ck리스트 받아오기.
문제2. 한글 제목 오류남.

There was an unexpected error (type=Internal Server Error, status=500).
### Error updating database. Cause: java.sql.SQLSyntaxErrorException:
(conn=1535) You have an error in your SQL syntax; check the manual that
corresponds to your MariaDB server version for the right syntax to use
near '워렌버핏 ### The error may exist in
com/gd/sakila/mapper/FilmMapper.xml ### The error may involve
com.gd.sakila.mapper.FilmMapper.insertFilm-Inline ### The error occurred
while setting parameters ### SQL: INSERT INTO film( title ,description
,release_year ,language_id ,original_laguage_id ,reantal_duration
,rental_rate ,length ,replacement_cost ,rating ,special_features)
VALUES( 한국의 워렌버핏 ,1 ,1 ,3 ,2 ,0 ,0.0 ,1 ,2 ,G ,) ### Cause:
java.sql.SQLSyntaxErrorException: (conn=1535) You have an error in your
SQL syntax; check the manual that corresponds to your MariaDB server
version for the right syntax to use near '워렌버핏 ; bad SQL grammar [];
nested exception is java.sql.SQLSyntaxErrorException: (conn=1535) You
have an error in your SQL syntax; check the manual that corresponds to
your MariaDB server version for the right syntax to use near '워렌버핏
org.springframework.jdbc.BadSqlGrammarException:
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException:
(conn=1535) You have an error in your SQL syntax; check the manual that
corresponds to your MariaDB server version for the right syntax to use
near '워렌버핏
### The error may exist in com/gd/sakila/mapper/FilmMapper.xml
### The error may involve
com.gd.sakila.mapper.FilmMapper.insertFilm-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO     film(  title      ,description
,release_year      ,language_id      ,original_laguage_id
,reantal_duration      ,rental_rate      ,length      ,replacement_cost
,rating      ,special_features)          VALUES( 한국의 워렌버핏      ,1
,1      ,3      ,2      ,0      ,0.0      ,1      ,2      ,G      ,)
### Cause: java.sql.SQLSyntaxErrorException: (conn=1535) You have an
error in your SQL syntax; check the manual that corresponds to your
MariaDB server version for the right syntax to use near '워렌버핏
; bad SQL grammar []; nested exception is
java.sql.SQLSyntaxErrorException: (conn=1535) You have an error in your
SQL syntax; check the manual that corresponds to your MariaDB server
version for the right syntax to use near '워렌버핏